use crate::{
    config::{RenderConfig, ReprKind},
    model::{
        common::Version,
        types::{EnumDef, EnumValue, TypesPage},
    },
};

pub fn render_types_module(types_page: &TypesPage, config: &RenderConfig) -> String {
    let mut out = String::new();

    out.push_str("// This file is generated by nm-codegen.\n");
    out.push_str("// Do not edit manually.\n\n");

    if !types_page.description.is_empty() {
        out.push_str(&render_source_doc(types_page.source_url.as_deref(), ""));
        out.push_str(&render_doc(&types_page.description, ""));
        out.push_str("\n");
    }

    let visible_enums: Vec<EnumAnalysis<'_>> = types_page
        .enums
        .iter()
        .filter(|e| is_visible_since(e.since.as_ref(), config.target_version.as_ref()))
        .map(|e| EnumAnalysis::new(e, config))
        .collect();

    if visible_enums.iter().any(EnumAnalysis::is_bitflags) {
        out.push_str("use bitflags::bitflags;\n\n");
    }

    for analysis in &visible_enums {
        maybe_warn_bitflags_misclassification(analysis);
        maybe_warn_duplicate_values(analysis);

        if let Some(rendered) = render_enum(analysis, config) {
            out.push_str(&rendered);
            out.push_str("\n\n");
        }
    }

    out
}

fn render_enum(analysis: &EnumAnalysis<'_>, config: &RenderConfig) -> Option<String> {
    if analysis.is_bitflags() {
        render_bitflags(analysis, config)
    } else {
        render_normal_enum(analysis, config)
    }
}

fn render_normal_enum(analysis: &EnumAnalysis<'_>, config: &RenderConfig) -> Option<String> {
    let target = config.target_version.as_ref();
    let e = analysis.enum_def;
    let repr = analysis.repr;
    let repr_ty = repr.rust_type();
    let normalizer = NameNormalizer::new(e, config);
    let canonical_groups = analysis.canonical_groups(target);
    let alias_groups = analysis.aliases(target);

    if canonical_groups.is_empty() {
        return None;
    }

    let mut out = String::new();

    out.push_str(&render_source_doc(e.source_url.as_deref(), ""));
    out.push_str(&render_doc(&e.description, ""));
    out.push_str(&render_since_deprecated_doc(
        e.since.as_ref(),
        effective_deprecated(e.deprecated.as_ref(), target),
        "",
    ));
    out.push_str(&format!(
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub enum {} {{\n",
        e.name
    ));

    for group in &canonical_groups {
        let variant_name = normalizer.normalize_variant(&group.canonical.name);

        out.push_str(&render_doc(&group.canonical.description, "    "));
        out.push_str(&render_since_deprecated_doc(
            group.canonical.since.as_ref(),
            effective_deprecated(group.canonical.deprecated.as_ref(), target),
            "    ",
        ));
        out.push_str(&format!("    {},\n\n", variant_name));
    }

    out.push_str(&format!(
        "    /// An unknown value not covered by the known enum variants.\n    Other({}),\n",
        repr_ty
    ));
    out.push_str("}\n\n");

    out.push_str(&format!("impl From<{}> for {} {{\n", repr_ty, e.name));
    out.push_str(&format!(
        "    fn from(value: {}) -> Self {{\n        match value {{\n",
        repr_ty
    ));

    for group in &canonical_groups {
        let variant_name = normalizer.normalize_variant(&group.canonical.name);
        out.push_str(&format!(
            "            {} => Self::{},\n",
            normalize_numeric_literal(group.value, repr),
            variant_name
        ));
    }

    out.push_str("            other => Self::Other(other),\n");
    out.push_str("        }\n    }\n}\n\n");

    out.push_str(&format!("impl From<{}> for {} {{\n", e.name, repr_ty));
    out.push_str(&format!(
        "    fn from(value: {}) -> Self {{\n        match value {{\n",
        e.name
    ));

    for group in &canonical_groups {
        let variant_name = normalizer.normalize_variant(&group.canonical.name);
        out.push_str(&format!(
            "            {}::{} => {},\n",
            e.name,
            variant_name,
            normalize_numeric_literal(group.value, repr)
        ));
    }

    out.push_str(&format!("            {}::Other(v) => v,\n", e.name));
    out.push_str("        }\n    }\n}\n");

    if !alias_groups.is_empty() {
        out.push_str("\n");
        out.push_str(&format!("impl {} {{\n", e.name));

        for alias in alias_groups {
            let alias_name = normalizer.normalize_variant(&alias.alias.name);
            let canonical_name = normalizer.normalize_variant(&alias.canonical.name);
            let alias_deprecated = effective_deprecated(alias.alias.deprecated.as_ref(), target);

            out.push_str(&render_alias_doc(
                &e.name,
                &canonical_name,
                alias.alias.since.as_ref(),
                alias_deprecated,
                "    ",
            ));

            out.push_str("    #[allow(non_upper_case_globals)]\n");

            if alias_deprecated.is_some() {
                out.push_str(&format!(
                    "    #[deprecated(note = \"Use `{}` instead\")]\n",
                    canonical_name
                ));
            }

            out.push_str(&format!(
                "    pub const {}: Self = Self::{};\n\n",
                alias_name, canonical_name
            ));
        }

        out.push_str("}\n");
    }

    Some(out)
}

fn render_bitflags(analysis: &EnumAnalysis<'_>, config: &RenderConfig) -> Option<String> {
    let target = config.target_version.as_ref();
    let e = analysis.enum_def;
    let normalizer = NameNormalizer::new(e, config);
    let visible_values = &analysis.visible_values;

    if visible_values.is_empty() {
        return None;
    }

    let mut out = String::new();

    out.push_str(&render_source_doc(e.source_url.as_deref(), ""));
    out.push_str(&render_doc(&e.description, ""));
    out.push_str(&render_since_deprecated_doc(
        e.since.as_ref(),
        effective_deprecated(e.deprecated.as_ref(), target),
        "",
    ));
    out.push_str(&format!(
        "bitflags! {{\n    pub struct {}: u32 {{\n",
        e.name
    ));

    for (i, v) in visible_values.iter().enumerate() {
        let const_name = normalizer.normalize_bitflags_const(&v.name);
        out.push_str(&render_doc(&v.description, "        "));
        out.push_str(&render_since_deprecated_doc(
            v.since.as_ref(),
            effective_deprecated(v.deprecated.as_ref(), target),
            "        ",
        ));
        out.push_str(&format!(
            "        const {} = {};\n",
            const_name,
            normalize_bitflags_literal(&v.value)
        ));

        if i != visible_values.len() - 1 {
            out.push_str("\n");
        }
    }

    out.push_str("    }\n}\n");
    Some(out)
}

fn detect_repr(e: &EnumDef, visible_values: &[&EnumValue], config: &RenderConfig) -> ReprKind {
    if let Some(repr) = config.repr_overrides.get(&e.name) {
        return *repr;
    }

    let has_negative = visible_values.iter().any(|v| v.has_negative_sign());

    if has_negative {
        ReprKind::I32
    } else {
        ReprKind::U32
    }
}

fn normalize_numeric_literal(value: &str, repr: ReprKind) -> String {
    let v = value.trim();
    match repr {
        ReprKind::I32 => v.to_string(),
        ReprKind::U32 => format!("{v}u32"),
    }
}

fn normalize_bitflags_literal(value: &str) -> String {
    format!("{}u32", value.trim())
}

fn render_source_doc(source_url: Option<&str>, indent: &str) -> String {
    match source_url {
        Some(url) => format!("{indent}/// Source: {url}\n{indent}///\n"),
        None => String::new(),
    }
}

fn render_doc(lines: &[String], indent: &str) -> String {
    let mut out = String::new();

    if lines.is_empty() {
        return String::new();
    }

    for line in lines {
        if line.trim().is_empty() {
            out.push_str(&format!("{indent}///\n"));
        } else {
            out.push_str(&format!("{indent}/// {}\n", line.trim()));
        }
    }

    out
}

fn render_since_deprecated_doc(
    since: Option<&Version>,
    deprecated: Option<&Version>,
    indent: &str,
) -> String {
    if since.is_none() && deprecated.is_none() {
        return String::new();
    }

    let mut parts = Vec::new();

    if let Some(v) = since {
        parts.push(format!("Since {}.{}", v.major, v.minor));
    }

    if let Some(v) = deprecated {
        parts.push(format!("Deprecated since {}.{}", v.major, v.minor));
    }

    let joined = parts.join("; ");

    format!("{indent}///\n{indent}/// _Generator note:_ {}.\n", joined)
}

fn render_alias_doc(
    enum_name: &str,
    canonical_name: &str,
    since: Option<&Version>,
    deprecated: Option<&Version>,
    indent: &str,
) -> String {
    let mut out = String::new();

    out.push_str(&format!(
        "{indent}/// Alias for [`{}::{}`].\n",
        enum_name, canonical_name
    ));
    out.push_str(&format!("{indent}///\n"));
    out.push_str(&render_since_deprecated_doc(since, deprecated, indent));

    if deprecated.is_some() {
        out.push_str(&format!(
            "{indent}/// Prefer using [`{}::{}`] directly.\n",
            enum_name, canonical_name
        ));
    }

    out
}

struct NameNormalizer<'a> {
    enum_name: &'a str,
    prefix: String,
    config: &'a RenderConfig,
}

impl<'a> NameNormalizer<'a> {
    fn new(e: &'a EnumDef, config: &'a RenderConfig) -> Self {
        let prefix = config
            .enum_prefix_overrides
            .get(&e.name)
            .cloned()
            .unwrap_or_else(|| camel_to_screaming_snake(&e.name));

        Self {
            enum_name: &e.name,
            prefix,
            config,
        }
    }

    fn normalize_variant(&self, raw: &str) -> String {
        let tail = self.strip_prefix(raw);

        if let Some(mapped) = self
            .config
            .variant_name_overrides
            .get(self.enum_name)
            .and_then(|m| m.get(tail))
        {
            return mapped.clone();
        }

        let mut result = tail
            .split(|c: char| !c.is_ascii_alphanumeric())
            .filter(|s| !s.is_empty())
            .map(pascal_part)
            .collect::<String>();

        if result.is_empty() {
            result = "Unknown".to_string();
        }

        if result
            .chars()
            .next()
            .map(|c| c.is_ascii_digit())
            .unwrap_or(false)
        {
            result = format!("_{}", result);
        }

        result
    }

    fn normalize_bitflags_const(&self, raw: &str) -> String {
        let tail = self.strip_prefix(raw);

        if let Some(mapped) = self
            .config
            .variant_name_overrides
            .get(self.enum_name)
            .and_then(|m| m.get(tail))
        {
            return mapped.clone();
        }

        let mut result = tail
            .trim_matches('_')
            .split(|c: char| !c.is_ascii_alphanumeric())
            .filter(|s| !s.is_empty())
            .map(|s| s.to_ascii_uppercase())
            .collect::<Vec<_>>()
            .join("_");

        if result.is_empty() {
            result = "Unknown".to_string();
        }

        if result
            .chars()
            .next()
            .map(|c| c.is_ascii_digit())
            .unwrap_or(false)
        {
            result = format!("_{}", result);
        }

        result
    }

    fn strip_prefix<'b>(&self, raw: &'b str) -> &'b str {
        let tail = strip_prefix_loose(raw, &self.prefix);

        if tail == raw {
            eprintln!(
                "[WARN] failed to strip prefix: enum={:?}, prefix={:?}, raw={:?}",
                self.enum_name, self.prefix, raw
            );
        }

        tail
    }
}

fn strip_prefix_loose<'a>(raw: &'a str, prefix: &str) -> &'a str {
    if let Some(tail) = raw.strip_prefix(prefix) {
        return tail.trim_start_matches('_');
    }

    if let Some(alt_prefix) = singular_plural_tolerant_prefix(prefix, raw) {
        if let Some(tail) = raw.strip_prefix(&alt_prefix) {
            return tail.trim_start_matches('_');
        }
    }

    raw
}

fn singular_plural_tolerant_prefix(prefix: &str, raw: &str) -> Option<String> {
    let prefix_parts: Vec<&str> = prefix.split('_').collect();
    let raw_parts: Vec<&str> = raw.split('_').collect();

    if prefix_parts.is_empty() || prefix_parts.len() > raw_parts.len() {
        return None;
    }

    let mut matched = Vec::with_capacity(prefix_parts.len());

    for (i, p) in prefix_parts.iter().enumerate() {
        let r = raw_parts[i];

        if *p == r {
            matched.push(r);
            continue;
        }

        let is_last = i == prefix_parts.len() - 1;
        if is_last && equal_except_trailing_s(p, r) {
            matched.push(r);
            continue;
        }

        return None;
    }

    Some(matched.join("_"))
}

fn equal_except_trailing_s(a: &str, b: &str) -> bool {
    a == b || strip_one_trailing_s(a) == b || a == strip_one_trailing_s(b)
}

fn strip_one_trailing_s(s: &str) -> &str {
    s.strip_suffix('S').unwrap_or(s)
}

fn camel_to_screaming_snake(input: &str) -> String {
    let chars: Vec<char> = input.chars().collect();
    let mut out = String::new();

    for i in 0..chars.len() {
        let ch = chars[i];

        let prev = if i > 0 { Some(chars[i - 1]) } else { None };
        let next = if i + 1 < chars.len() {
            Some(chars[i + 1])
        } else {
            None
        };

        let is_boundary = i > 0
            && ch.is_ascii_uppercase()
            && (prev.is_some_and(|c| c.is_ascii_lowercase() || c.is_ascii_digit())
                || (prev.is_some_and(|c| c.is_ascii_uppercase()))
                    && next.is_some_and(|c| c.is_ascii_lowercase()));

        if is_boundary {
            out.push('_');
        }

        out.push(ch.to_ascii_uppercase());
    }

    out
}

fn pascal_part(part: &str) -> String {
    let mut chars = part.chars();
    match chars.next() {
        Some(first) => {
            let mut out = String::new();
            out.extend(first.to_uppercase());
            out.push_str(&chars.as_str().to_ascii_lowercase());
            out
        }
        None => String::new(),
    }
}

fn maybe_warn_bitflags_misclassification(analysis: &EnumAnalysis<'_>) {
    let has_hex = analysis.is_bitflags();
    let numeric_shape = classify_numeric_shape_refs(&analysis.visible_values);

    match (has_hex, numeric_shape) {
        (true, NumericShape::NotBitflagsLike) => {
            eprintln!(
                "[WARN] enum {:?} was generated as bitflags because values are hex-formatted, \
                but the numeric pattern does not look like a typical bitflags set",
                analysis.enum_def.name
            );
        }

        (false, NumericShape::BitflagsLike) => {
            eprintln!(
                "[WARN] enum {:?} was generated as a normal enum, \
                but the numeric pattern looks like bitflags (all non-zero values are powers of two)",
                analysis.enum_def.name
            );
        }

        _ => {}
    }
}

fn maybe_warn_duplicate_values(analysis: &EnumAnalysis<'_>) {
    for group in &analysis.value_groups {
        if group.entries.len() > 1 {
            let names = group
                .entries
                .iter()
                .map(|v| v.name.as_str())
                .collect::<Vec<_>>()
                .join(", ");

            eprintln!(
                "[WARN] enum {:?} has multiple visible names for value {}: {}",
                analysis.enum_def.name, group.value, names
            );
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum NumericShape {
    Unknown,
    BitflagsLike,
    NotBitflagsLike,
}

fn classify_numeric_shape_refs(values: &[&EnumValue]) -> NumericShape {
    if values.is_empty() {
        return NumericShape::Unknown;
    }

    let mut saw_non_zero = false;

    for v in values {
        let raw = v.value.trim();

        if raw.starts_with('-') {
            return NumericShape::NotBitflagsLike;
        }

        let n = if raw.starts_with("0x") || raw.starts_with("0X") {
            match u32::from_str_radix(&raw[2..], 16) {
                Ok(v) => v,
                Err(_) => return NumericShape::Unknown,
            }
        } else {
            match raw.parse::<u32>() {
                Ok(v) => v,
                Err(_) => return NumericShape::Unknown,
            }
        };

        if n == 0 {
            continue;
        }

        saw_non_zero = true;

        if !is_power_of_two(n) {
            return NumericShape::NotBitflagsLike;
        }
    }

    if saw_non_zero {
        NumericShape::BitflagsLike
    } else {
        NumericShape::Unknown
    }
}

fn is_power_of_two(n: u32) -> bool {
    n != 0 && (n & (n - 1)) == 0
}

struct ValueGroup<'a> {
    value: &'a str,
    entries: Vec<&'a EnumValue>,
}

struct CanonicalGroup<'a> {
    value: &'a str,
    canonical: &'a EnumValue,
}

struct AliasEntry<'a> {
    canonical: &'a EnumValue,
    alias: &'a EnumValue,
}

struct EnumAnalysis<'a> {
    enum_def: &'a EnumDef,
    visible_values: Vec<&'a EnumValue>,
    value_groups: Vec<ValueGroup<'a>>,
    repr: ReprKind,
    bitflags: bool,
}

impl<'a> EnumAnalysis<'a> {
    fn new(e: &'a EnumDef, config: &RenderConfig) -> Self {
        let target = config.target_version.as_ref();
        let visible_values: Vec<&EnumValue> = e
            .values
            .iter()
            .filter(|v| is_visible_since(v.since.as_ref(), target))
            .collect();
        let value_groups = group_values_by_numeric(&visible_values);
        let repr = detect_repr(e, &visible_values, config);
        let bitflags = visible_values.iter().any(|v| v.is_hex());

        Self {
            enum_def: e,
            visible_values,
            value_groups,
            repr,
            bitflags,
        }
    }

    fn is_bitflags(&self) -> bool {
        self.bitflags
    }

    fn canonical_groups(&self, target_version: Option<&Version>) -> Vec<CanonicalGroup<'a>> {
        self.value_groups
            .iter()
            .map(|group| {
                let canonical = pick_canonical_entry(&group.entries, target_version);
                CanonicalGroup {
                    value: group.value,
                    canonical,
                }
            })
            .collect()
    }

    fn aliases(&self, target_version: Option<&Version>) -> Vec<AliasEntry<'a>> {
        collect_aliases(&self.value_groups, target_version)
    }
}

fn group_values_by_numeric<'a>(visible_values: &[&'a EnumValue]) -> Vec<ValueGroup<'a>> {
    let mut groups: Vec<ValueGroup<'a>> = Vec::new();

    for value in visible_values {
        let key = value.value.trim();

        if let Some(group) = groups.iter_mut().find(|g| g.value == key) {
            group.entries.push(*value);
        } else {
            groups.push(ValueGroup {
                value: key,
                entries: vec![*value],
            });
        }
    }

    groups
}

fn pick_canonical_entry<'a>(
    entries: &[&'a EnumValue],
    target_version: Option<&Version>,
) -> &'a EnumValue {
    let mut best = entries[0];

    for candidate in entries.iter().copied().skip(1) {
        if is_better_canonical(candidate, best, target_version) {
            best = candidate;
        }
    }

    best
}

fn is_better_canonical(
    candidate: &EnumValue,
    current: &EnumValue,
    target_version: Option<&Version>,
) -> bool {
    let candidate_active = is_active_at_target(candidate.deprecated.as_ref(), target_version);
    let current_active = is_active_at_target(current.deprecated.as_ref(), target_version);

    match (candidate_active, current_active) {
        (true, false) => return true,
        (false, true) => return false,
        _ => {}
    }

    match compare_option_version(candidate.since.as_ref(), current.since.as_ref()) {
        std::cmp::Ordering::Greater => true,
        std::cmp::Ordering::Less => false,
        std::cmp::Ordering::Equal => true,
    }
}

fn compare_option_version(a: Option<&Version>, b: Option<&Version>) -> std::cmp::Ordering {
    match (a, b) {
        (Some(a), Some(b)) => a.cmp(b),
        (Some(_), None) => std::cmp::Ordering::Greater,
        (None, Some(_)) => std::cmp::Ordering::Less,
        (None, None) => std::cmp::Ordering::Equal,
    }
}

fn collect_aliases<'a>(
    groups: &[ValueGroup<'a>],
    target_version: Option<&Version>,
) -> Vec<AliasEntry<'a>> {
    let mut aliases = Vec::new();

    for group in groups {
        if group.entries.len() <= 1 {
            continue;
        }

        let canonical = pick_canonical_entry(&group.entries, target_version);

        for entry in &group.entries {
            if std::ptr::eq(*entry, canonical) {
                continue;
            }

            aliases.push(AliasEntry {
                canonical,
                alias: entry,
            });
        }
    }

    aliases
}

fn is_visible_since(since: Option<&Version>, target_version: Option<&Version>) -> bool {
    match (since, target_version) {
        (_, None) => true,
        (None, Some(_)) => true,
        (Some(since), Some(target)) => since <= target,
    }
}

fn is_active_at_target(deprecated: Option<&Version>, target_version: Option<&Version>) -> bool {
    match target_version {
        None => deprecated.is_none(),
        Some(target) => match deprecated {
            None => true,
            Some(dep) => dep > target,
        },
    }
}

fn effective_deprecated<'a>(
    deprecated: Option<&'a Version>,
    target_version: Option<&Version>,
) -> Option<&'a Version> {
    match target_version {
        None => deprecated,
        Some(target) => match deprecated {
            Some(dep) if dep <= target => Some(dep),
            _ => None,
        },
    }
}
