use crate::{
    config::{RenderConfig, ReprKind},
    model::types::{EnumDef, EnumValue},
};

pub fn render_types_module(enums: &[EnumDef], config: &RenderConfig) -> String {
    let mut out = String::new();

    out.push_str("// This file is generated by nm-codegen.\n");
    out.push_str("// Do not edit manually.\n\n");

    if enums.iter().any(|e| e.is_bitflags_by_value()) {
        out.push_str("use bitflags::bitflags;\n\n");
    }

    for en in enums {
        maybe_warn_bitflags_misclassification(en);
        out.push_str(&render_enum(en, config));
        out.push_str("\n\n");
    }

    out
}

pub fn render_enum(e: &EnumDef, config: &RenderConfig) -> String {
    if e.is_bitflags_by_value() {
        render_bitflags(e, config)
    } else {
        render_normal_enum(e, config)
    }
}

fn render_normal_enum(e: &EnumDef, config: &RenderConfig) -> String {
    let repr = detect_repr(e, config);
    let repr_ty = repr.rust_type();
    let normalizer = NameNormalizer::new(e, config);

    let mut out = String::new();

    out.push_str(&render_source_doc(e.source_url.as_deref(), ""));
    out.push_str(&render_doc(&e.description, ""));
    out.push_str(&format!(
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub enum {} {{\n",
        e.name
    ));

    for v in &e.values {
        let variant_name = normalizer.normalize_variant(&v.name);
        out.push_str(&render_doc(&v.description, "    "));
        out.push_str(&format!("    {},\n\n", variant_name));
    }

    out.push_str(&format!(
        "    /// An unknown value not covered by the known enum variants.\n    Other({}),\n",
        repr_ty
    ));
    out.push_str("}\n\n");

    out.push_str(&format!("impl From<{}> for {} {{\n", repr_ty, e.name));
    out.push_str(&format!(
        "    fn from(value: {}) -> Self {{\n        match value {{\n",
        repr_ty
    ));

    for v in &e.values {
        let variant_name = normalizer.normalize_variant(&v.name);
        out.push_str(&format!(
            "            {} => Self::{},\n",
            normalize_numeric_literal(&v.value, repr),
            variant_name
        ));
    }

    out.push_str("            other => Self::Other(other),\n");
    out.push_str("        }\n    }\n}\n\n");

    out.push_str(&format!("impl From<{}> for {} {{\n", e.name, repr_ty));
    out.push_str(&format!(
        "    fn from(value: {}) -> Self {{\n        match value {{\n",
        e.name
    ));

    for v in &e.values {
        let variant_name = normalizer.normalize_variant(&v.name);
        out.push_str(&format!(
            "            {}::{} => {},\n",
            e.name,
            variant_name,
            normalize_numeric_literal(&v.value, repr)
        ));
    }

    out.push_str(&format!("            {}::Other(v) => v,\n", e.name));
    out.push_str("        }\n    }\n}\n");

    out
}

fn render_bitflags(e: &EnumDef, config: &RenderConfig) -> String {
    let normalizer = NameNormalizer::new(e, config);
    let mut out = String::new();

    out.push_str(&render_source_doc(e.source_url.as_deref(), ""));
    out.push_str(&render_doc(&e.description, ""));
    out.push_str(&format!(
        "bitflags! {{\n    pub struct {}: u32 {{\n",
        e.name
    ));

    for (i, v) in e.values.iter().enumerate() {
        let const_name = normalizer.normalize_bitflags_const(&v.name);
        out.push_str(&render_doc(&v.description, "        "));
        out.push_str(&format!(
            "        const {} = {};\n",
            const_name,
            normalize_bitflags_literal(&v.value)
        ));

        if i != e.values.len() - 1 {
            out.push_str("\n");
        }
    }

    out.push_str("    }\n}\n");
    out
}

fn detect_repr(e: &EnumDef, config: &RenderConfig) -> ReprKind {
    if let Some(repr) = config.repr_overrides.get(&e.name) {
        return *repr;
    }

    if e.has_negative_value() {
        ReprKind::I32
    } else {
        ReprKind::U32
    }
}

fn normalize_numeric_literal(value: &str, repr: ReprKind) -> String {
    let v = value.trim();
    match repr {
        ReprKind::I32 => v.to_string(),
        ReprKind::U32 => format!("{v}u32"),
    }
}

fn normalize_bitflags_literal(value: &str) -> String {
    format!("{}u32", value.trim())
}

fn render_source_doc(source_url: Option<&str>, ident: &str) -> String {
    match source_url {
        Some(url) => format!("{ident}/// Source: {url}\n{ident}///\n"),
        None => String::new(),
    }
}

fn render_doc(lines: &[String], indent: &str) -> String {
    let mut out = String::new();

    if lines.is_empty() {
        return String::new();
    }

    for line in lines {
        if line.trim().is_empty() {
            out.push_str(&format!("{indent}///\n"));
        } else {
            out.push_str(&format!("{indent}/// {}\n", line.trim()));
        }
    }

    out
}

struct NameNormalizer<'a> {
    enum_name: &'a str,
    prefix: String,
    config: &'a RenderConfig,
}

impl<'a> NameNormalizer<'a> {
    fn new(e: &'a EnumDef, config: &'a RenderConfig) -> Self {
        let prefix = config
            .enum_prefix_overrides
            .get(&e.name)
            .cloned()
            .unwrap_or_else(|| camel_to_screaming_snake(&e.name));

        Self {
            enum_name: &e.name,
            prefix,
            config,
        }
    }

    fn normalize_variant(&self, raw: &str) -> String {
        let tail = self.strip_prefix(raw);

        if let Some(mapped) = self
            .config
            .variant_name_overrides
            .get(self.enum_name)
            .and_then(|m| m.get(tail))
        {
            return mapped.clone();
        }

        let mut result = tail
            .split(|c: char| !c.is_ascii_alphanumeric())
            .filter(|s| !s.is_empty())
            .map(pascal_part)
            .collect::<String>();

        if result.is_empty() {
            result = "Unknown".to_string();
        }

        if result.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
            result = format!("_{}", result);
        }

        result
    }

    fn normalize_bitflags_const(&self, raw: &str) -> String {
        let tail = self.strip_prefix(raw);

        if let Some(mapped) = self
            .config
            .variant_name_overrides
            .get(self.enum_name)
            .and_then(|m| m.get(tail))
        {
            return mapped.clone();
        }

        let mut result = tail
            .trim_matches('_')
            .split(|c: char| !c.is_ascii_alphanumeric())
            .filter(|s| !s.is_empty())
            .map(|s| s.to_ascii_uppercase())
            .collect::<Vec<_>>()
            .join("_");

        if result.is_empty() {
            result = "Unknown".to_string();
        }

        if result.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
            result = format!("_{}", result);
        }

        result
    }

    fn strip_prefix<'b>(&self, raw: &'b str) -> &'b str {
        let tail = strip_prefix_loose(raw, &self.prefix);

        if tail == raw {
            eprintln!(
                "[WARN] failed to strip prefix: enum={:?}, prefix={:?}, raw{:?}",
                self.enum_name, self.prefix, raw
            );
        }

        tail
    }
}

fn strip_prefix_loose<'a>(raw: &'a str, prefix: &str) -> &'a str {
    if let Some(tail) = raw.strip_prefix(prefix) {
        return tail.trim_start_matches('_');
    }

    if let Some(alt_prefix) = singular_plural_tolerant_prefix(prefix, raw) {
        if let Some(tail) = raw.strip_prefix(&alt_prefix) {
            return tail.trim_start_matches('_');
        }
    }

    raw
}

fn singular_plural_tolerant_prefix(prefix: &str, raw: &str) -> Option<String> {
    let prefix_parts: Vec<&str> = prefix.split('_').collect();
    let raw_parts: Vec<&str> = raw.split('_').collect();

    if prefix_parts.is_empty() || prefix_parts.len() > raw_parts.len() {
        return None;
    }

    let mut mached = Vec::with_capacity(prefix_parts.len());

    for (i, p) in prefix_parts.iter().enumerate() {
        let r = raw_parts[i];

        if *p == r {
            mached.push(r);
            continue;
        }

        let is_last = i == prefix_parts.len() - 1;
        if is_last && equal_except_trailing_s(p, r) {
            mached.push(r);
            continue;
        }

        return None;
    }

    Some(mached.join("_"))
}

fn equal_except_trailing_s(a: &str, b: &str) -> bool {
    a == b || strip_one_trailing_s(a) == b || a == strip_one_trailing_s(b)
}

fn strip_one_trailing_s(s: &str) -> &str {
    s.strip_suffix('S').unwrap_or(s)
}

fn camel_to_screaming_snake(input: &str) -> String {
    let chars: Vec<char> = input.chars().collect();
    let mut out = String::new();

    for i in 0..chars.len() {
        let ch = chars[i];

        let prev = if i > 0 { Some(chars[i - 1]) } else { None };
        let next = if i + 1 < chars.len() {
            Some(chars[i + 1])
        } else {
            None
        };

        let is_boundary =
            i > 0
                && ch.is_ascii_uppercase()
                && (
                    // fooBar
                    prev.is_some_and(|c| c.is_ascii_lowercase() || c.is_ascii_digit())
                    ||
                    // HTTPServer -> HTTP_Server
                    (prev.is_some_and(|c| c.is_ascii_uppercase()))
                        && next.is_some_and(|c| c.is_ascii_lowercase())
                );

        if is_boundary {
            out.push('_');
        }

        out.push(ch.to_ascii_uppercase());
    }

    out
}

fn pascal_part(part: &str) -> String {
    let mut chars = part.chars();
    match chars.next() {
        Some(first) => {
            let mut out = String::new();
            out.extend(first.to_uppercase());
            out.push_str(&chars.as_str().to_ascii_lowercase());
            out
        }
        None => String::new(),
    }
}

fn maybe_warn_bitflags_misclassification(e: &EnumDef) {
    let has_hex = e.is_bitflags_by_value();
    let numeric_shape = classify_numeric_shape(&e.values);

    match (has_hex, numeric_shape) {
        (true, NumericShape::NotBitflagsLike) => {
            eprintln!(
                "[WARN] enum {:?} was generated as bitflags because values are hex-formatted,\
                but the numeric pattern does not look like a typical bitflags set",
                e.name
            );
        }

        (false, NumericShape::BitflagsLike) => {
            eprintln!(
                "[WARN] enum {:?} was generated as a normal enum, \
                but the numeric pattern looks like bitflags (all non-zero values are powers of two)",
                e.name
            );
        }

        _ => {}
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum NumericShape {
    Unknown,
    BitflagsLike,
    NotBitflagsLike,
}

fn classify_numeric_shape(values: &[EnumValue]) -> NumericShape {
    if values.is_empty() {
        return NumericShape::Unknown;
    }

    let mut saw_non_zero = false;

    for v in values {
        let raw = v.value.trim();

        if raw.starts_with('-') {
            return NumericShape::NotBitflagsLike;
        }

        let n = if raw.starts_with("0x") || raw.starts_with("0X") {
            match u32::from_str_radix(&raw[2..], 16) {
                Ok(v) => v,
                Err(_) => return NumericShape::Unknown,
            }
        } else {
            match raw.parse::<u32>() {
                Ok(v) => v,
                Err(_) => return NumericShape::Unknown,
            }
        };

        if n == 0 {
            continue;
        }

        saw_non_zero = true;

        if !is_power_of_two(n) {
            return NumericShape::NotBitflagsLike;
        }
    }

    if saw_non_zero {
        NumericShape::BitflagsLike
    } else {
        NumericShape::Unknown
    }
}

fn is_power_of_two(n: u32) -> bool {
    n != 0 && (n & (n - 1)) == 0
}
